
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Suphi Can
 */

public class BankApp extends javax.swing.JFrame {

    /**
     * Creates new form BankApp
     */
    public BankApp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
        /**
     * @param args the command line arguments
     */
     CheckingAccount myCheckAccount = new CheckingAccount();
     SavingsAccount mySaveAccount = new SavingsAccount();
     
     public void starProg()
     {
        ownerName.setText(myCheckAccount.getOwner());
        checkBalance.setText(String.valueOf(myCheckAccount.getBalance())); 
        savingBalance.setText(String.valueOf(mySaveAccount.getBalance())); 
        iRate.setText(String.valueOf(mySaveAccount.getAnnualInterestRate()));
        overDraft.setText(String.valueOf(myCheckAccount.getFundFee()));
     }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BankApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BankApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BankApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BankApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        
        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new BankApp().setVisible(true);
//           }
//        });
        
    }
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jDialog1 = new javax.swing.JDialog();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cWithdraw = new javax.swing.JTextField();
        cDeposit = new javax.swing.JTextField();
        sDeposit = new javax.swing.JTextField();
        sWithdraw = new javax.swing.JTextField();
        cDepositButton = new javax.swing.JButton();
        sDepositButton = new javax.swing.JButton();
        sWithdrawButton = new javax.swing.JButton();
        cWithdrawButton = new javax.swing.JButton();
        ownerName = new javax.swing.JLabel();
        checkBalance = new javax.swing.JLabel();
        overDraft = new javax.swing.JLabel();
        savingBalance = new javax.swing.JLabel();
        iRate = new javax.swing.JLabel();

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel7.setText("Balance:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jDialog1.setAlwaysOnTop(true);
        jDialog1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("OK");
        jDialog1.getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("You don't have enough balance.");
        jDialog1.getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 210, 40));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Saving Account");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Owner:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Checking Account");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setText("Overdraft Fees:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setText("Balance:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel6.setText("Balance:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel8.setText("Interest Rate:");

        cWithdraw.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        cWithdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cWithdrawActionPerformed(evt);
            }
        });

        cDeposit.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        cDeposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cDepositActionPerformed(evt);
            }
        });

        sDeposit.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        sDeposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sDepositActionPerformed(evt);
            }
        });

        sWithdraw.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        sWithdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sWithdrawActionPerformed(evt);
            }
        });

        cDepositButton.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        cDepositButton.setText("Deposit");
        cDepositButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cDepositButtonActionPerformed(evt);
            }
        });

        sDepositButton.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        sDepositButton.setText("Deposit");
        sDepositButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sDepositButtonActionPerformed(evt);
            }
        });

        sWithdrawButton.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        sWithdrawButton.setText("Withdraw");
        sWithdrawButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sWithdrawButtonActionPerformed(evt);
            }
        });

        cWithdrawButton.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        cWithdrawButton.setText("Withdraw");
        cWithdrawButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cWithdrawButtonActionPerformed(evt);
            }
        });

        ownerName.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        checkBalance.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        checkBalance.setText("0.00");

        overDraft.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        overDraft.setText("0.00");

        savingBalance.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        savingBalance.setText("0.00");

        iRate.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        iRate.setText("0.00");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(iRate))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(savingBalance)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(sDeposit)
                                    .addComponent(sWithdraw, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(overDraft)
                                        .addGap(109, 109, 109))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(checkBalance)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cWithdraw)
                                    .addComponent(cDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(sWithdrawButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sDepositButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cDepositButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cWithdrawButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ownerName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(123, 123, 123))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ownerName, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cDepositButton)
                    .addComponent(checkBalance))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cWithdraw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cWithdrawButton)
                    .addComponent(overDraft))
                .addGap(7, 7, 7)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(sDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sDepositButton)
                    .addComponent(savingBalance))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(sWithdraw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sWithdrawButton)
                    .addComponent(iRate))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cWithdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cWithdrawActionPerformed
        // TODO add your handling code here: 
    }//GEN-LAST:event_cWithdrawActionPerformed

    private void cDepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cDepositActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cDepositActionPerformed

    private void sDepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sDepositActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sDepositActionPerformed

    private void sWithdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sWithdrawActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sWithdrawActionPerformed

    private void cDepositButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cDepositButtonActionPerformed
    myCheckAccount.deposit(Double.parseDouble(cDeposit.getText()));
    checkBalance.setText(String.valueOf(myCheckAccount.getBalance())); 
    JOptionPane.showMessageDialog(this, "Deposit for Checking Account Succesfull.");
    }//GEN-LAST:event_cDepositButtonActionPerformed

    private void sDepositButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sDepositButtonActionPerformed
       mySaveAccount.deposit(Double.parseDouble(sDeposit.getText()));
       savingBalance.setText(String.valueOf(mySaveAccount.getBalance())); 
       JOptionPane.showMessageDialog(this, "Deposit for Saving Account Succesfull.");
    }//GEN-LAST:event_sDepositButtonActionPerformed

    private void cWithdrawButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cWithdrawButtonActionPerformed
        myCheckAccount.withdrawal(Double.parseDouble(cWithdraw.getText()));
        checkBalance.setText(String.valueOf(myCheckAccount.getBalance())); 
    }//GEN-LAST:event_cWithdrawButtonActionPerformed

    private void sWithdrawButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sWithdrawButtonActionPerformed
        mySaveAccount.withdrawal(Double.parseDouble(sWithdraw.getText()));
        savingBalance.setText(String.valueOf(mySaveAccount.getBalance())); 
    }//GEN-LAST:event_sWithdrawButtonActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JTextField cDeposit;
    public static javax.swing.JButton cDepositButton;
    private javax.swing.JTextField cWithdraw;
    private javax.swing.JButton cWithdrawButton;
    private static javax.swing.JLabel checkBalance;
    private static javax.swing.JLabel iRate;
    private javax.swing.JButton jButton1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private static javax.swing.JLabel overDraft;
    private static javax.swing.JLabel ownerName;
    private javax.swing.JTextField sDeposit;
    private javax.swing.JButton sDepositButton;
    private javax.swing.JTextField sWithdraw;
    private javax.swing.JButton sWithdrawButton;
    private static javax.swing.JLabel savingBalance;
    // End of variables declaration//GEN-END:variables
}
